/*TODA VEZ QUE REIMPORTAR O BANCO, APAGA AS TABELAS ANTIGAS PARA EVITAR CONFLITOS*/
DROP TABLE IF EXISTS Produto;
DROP TABLE IF EXISTS Valor_produto;
DROP TABLE IF EXISTS Venda;
DROP TABLE IF EXISTS Vende_produto;
DROP TABLE IF EXISTS Recebimento;
DROP TABLE IF EXISTS Recebe_produto;

/* -------------------------------------------------------------------------- */


/* CRIAÇÃO DE TABELAS */
CREATE TABLE Produto (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Ativo BOOLEAN NOT NULL DEFAULT TRUE,
	Nome VARCHAR(100) NOT NULL 
);

CREATE TABLE Valor_produto (
	Id INT PRIMARY KEY NOT NULL,
	Data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Ativo BOOLEAN NOT NULL DEFAULT TRUE,
	Valor DOUBLE NOT NULL DEFAULT 0,
	Produto_id INT NOT NULL,
	CONSTRAINT FK_PRODUTO_VALOR_PRODUTO 
        FOREIGN KEY (Produto_id) REFERENCES Produto(Id) ON UPDATE CASCADE 
);

CREATE TABLE Venda (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Ativo BOOLEAN NOT NULL DEFAULT TRUE,
	Nome_cliente VARCHAR(100) NOT NULL 
);

CREATE TABLE Vende_produto (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Quantidade DOUBLE NOT NULL DEFAULT 0,
	Venda_id INT NOT NULL,
	CONSTRAINT FK_VENDA_VENDE_PRODUTO 
        FOREIGN KEY (Venda_id) REFERENCES Venda(Id) ON UPDATE CASCADE 
);

CREATE TABLE Recebimento (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Ativo BOOLEAN NOT NULL DEFAULT TRUE,
	Nome_cliente VARCHAR(100) NOT NULL 
);

CREATE TABLE Recebe_produto (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Quantidade DOUBLE NOT NULL DEFAULT 0,
	Recebimento_id INT NOT NULL,
	CONSTRAINT FK_RECEBIMENTO_RECEBE_PRODUTO 
        FOREIGN KEY (Recebimento_id) REFERENCES Recebimento(Id) ON UPDATE CASCADE  
);

/* -------------------------------------------------------------------------- */


/* Popular o DB */
