/*TODA VEZ QUE REIMPORTAR O BANCO, APAGA AS TABELAS ANTIGAS PARA EVITAR CONFLITOS*/
DROP TABLE IF EXISTS Produto;
DROP TABLE IF EXISTS Valor;
DROP TABLE IF EXISTS Produto_valor;
DROP TABLE IF EXISTS Venda;
DROP TABLE IF EXISTS Vende_produto;
DROP TABLE IF EXISTS Recebimento;
DROP TABLE IF EXISTS Recebe_produto;

/* -------------------------------------------------------------------------- */


/* CRIAÇÃO DE TABELAS */
CREATE TABLE Produto (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	nome VARCHAR(100) NOT NULL 
);

CREATE TABLE Valor (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	valor DOUBLE NOT NULL DEFAULT 0 
);

CREATE TABLE Produto_valor (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	produto_id INT NOT NULL,
	valor_id INT NOT NULL,
	CONSTRAINT FK_PRODUTO_PRODUTO_VALOR 
        FOREIGN KEY (produto_id) REFERENCES Produto(id) ON UPDATE CASCADE,
    CONSTRAINT FK_VALOR_PRODUTO_VALOR 
        FOREIGN KEY (valor_id) REFERENCES Valor(id) ON UPDATE CASCADE 
);

CREATE TABLE Venda (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	nome_cliente VARCHAR(100) NOT NULL 
);

CREATE TABLE Vende_produto (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	quantidade DOUBLE NOT NULL DEFAULT 0,
	venda_id INT NOT NULL,
	produto_valor_id INT NOT NULL,
	CONSTRAINT FK_VENDA_VENDE_PRODUTO 
        FOREIGN KEY (venda_id) REFERENCES Venda(id) ON UPDATE CASCADE,
    CONSTRAINT FK_PRODUTO_VALOR_VENDE_PRODUTO 
        FOREIGN KEY (produto_valor_id) REFERENCES Produto_valor(id) ON UPDATE CASCADE 
);

CREATE TABLE Recebimento (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	nome_cliente VARCHAR(100) NOT NULL 
);

CREATE TABLE Recebe_produto (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	quantidade DOUBLE NOT NULL DEFAULT 0,
	recebimento_id INT NOT NULL, 
	produto_id INT NOT NULL,
	CONSTRAINT FK_RECEBIMENTO_RECEBE_PRODUTO 
        FOREIGN KEY (recebimento_id) REFERENCES Recebimento(id) ON UPDATE CASCADE, 
    CONSTRAINT FK_PRODUTO_RECEBE_PRODUTO 
        FOREIGN KEY (produto_id) REFERENCES Produto(id) ON UPDATE CASCADE 
);

/* -------------------------------------------------------------------------- */


/* Popular o DB */
